# Generated by Django 2.0.6 on 2018-07-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_diver_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='diver',
            name='data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
