# Generated by Django 2.0.6 on 2018-07-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_diver_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/boutique')),
            ],
        ),
    ]
