# Generated by Django 2.0.6 on 2018-07-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_boutiqueimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardimage',
            name='card',
        ),
        migrations.AddField(
            model_name='acceuilcard',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/panier_image'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CardImage',
        ),
    ]
