# Generated by Django 2.0.6 on 2018-07-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180717_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceuilcard',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='acceuilcard',
            name='image',
            field=models.ImageField(upload_to='uploads/card_images'),
        ),
    ]
