# Generated by Django 2.0.3 on 2018-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('cepage', models.TextField()),
                ('notes_degustation', models.TextField()),
                ('accords', models.TextField()),
                ('temperature', models.FloatField()),
                ('date_ajout', models.DateField()),
                ('prix', models.FloatField()),
                ('est_promo', models.BooleanField()),
                ('debut_promo', models.DateField()),
                ('fin_promo', models.DateField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='sous_cats',
            field=models.ManyToManyField(to='magasin.SousCategorie'),
        ),
    ]
