# Generated by Django 2.0.3 on 2018-06-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='magasin.Categorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='magasin.SousCategorie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='debut_promo',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fin_promo',
            field=models.DateField(blank=True),
        ),
    ]
