# Generated by Django 2.0.6 on 2018-06-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_auto_20180604_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='accords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='cepage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='debut_promo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='est_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fin_promo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='notes_degustation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
