# Generated by Django 2.0.6 on 2018-06-05 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_auto_20180605_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_ajout',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='souscategorie',
            name='nom',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='magasin.TypesProduit'),
        ),
    ]
