# Generated by Django 2.0.6 on 2018-06-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_auto_20180605_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='poid',
            field=models.FloatField(null=True, verbose_name='poid en gramme'),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='magasin.Marque'),
        ),
    ]
