# Generated by Django 2.0.3 on 2018-06-08 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_auto_20180606_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=5)),
                ('tel', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 8, 7, 14, 39, 635970, tzinfo=utc))),
                ('montant', models.FloatField()),
                ('est_panier', models.BooleanField()),
                ('envoie', models.BooleanField()),
                ('est_envoyee', models.BooleanField()),
                ('est_archivee', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magasin.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ContenuCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magasin.Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magasin.Produit')),
            ],
        ),
    ]
