# Generated by Django 2.0.3 on 2018-06-08 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_client_commande_contenucommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 7, 18, 31, 181730, tzinfo=utc)),
        ),
    ]
