# Generated by Django 2.0.3 on 2018-06-08 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_auto_20180608_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 12, 23, 27, 538171, tzinfo=utc)),
        ),
    ]
