# Generated by Django 2.0.3 on 2018-06-08 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_auto_20180608_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 13, 50, 18, 310191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commande',
            name='envoie',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='est_archivee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='est_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='est_panier',
            field=models.BooleanField(default=False),
        ),
    ]
