# Generated by Django 2.0.3 on 2018-06-08 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_auto_20180608_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='est_payee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 16, 13, 44, 430147, tzinfo=utc)),
        ),
    ]
