# Generated by Django 2.0.6 on 2018-06-19 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0016_auto_20180613_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 13, 15, 5, 840502, tzinfo=utc)),
        ),
    ]
