# Generated by Django 2.0.6 on 2018-06-19 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0017_auto_20180619_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 13, 17, 38, 29303, tzinfo=utc)),
        ),
    ]
