# Generated by Django 2.0.6 on 2018-06-19 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0018_auto_20180619_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 13, 28, 10, 437911, tzinfo=utc)),
        ),
    ]
