# Generated by Django 2.0.6 on 2018-06-22 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0020_auto_20180622_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 11, 50, 25, 14049, tzinfo=utc)),
        ),
    ]
