# Generated by Django 2.0.6 on 2018-07-25 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0021_auto_20180717_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='maj',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 15, 21, 19, 859943, tzinfo=utc)),
        ),
    ]
