# Generated by Django 2.0.6 on 2018-09-02 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0023_auto_20180726_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 22, 56, 25, 538108, tzinfo=utc)),
        ),
    ]
