# Generated by Django 2.0.6 on 2018-09-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180703_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
