CREATE TABLE auth_permission (
  id               integer,
  content_type_id  integer,
  codename         varchar(100),
  name             varchar(255)
);


INSERT INTO `auth_permission` (`id`, `content_type_id`, `codename`, `name`) VALUES
  (1, 1, 'add_logentry', 'Can add log entry'),
  (2, 1, 'change_logentry', 'Can change log entry'),
  (3, 1, 'delete_logentry', 'Can delete log entry'),
  (4, 2, 'add_permission', 'Can add permission'),
  (5, 2, 'change_permission', 'Can change permission'),
  (6, 2, 'delete_permission', 'Can delete permission'),
  (7, 3, 'add_group', 'Can add group'),
  (8, 3, 'change_group', 'Can change group'),
  (9, 3, 'delete_group', 'Can delete group'),
  (10, 4, 'add_contenttype', 'Can add content type'),
  (11, 4, 'change_contenttype', 'Can change content type'),
  (12, 4, 'delete_contenttype', 'Can delete content type'),
  (13, 5, 'add_session', 'Can add session'),
  (14, 5, 'change_session', 'Can change session'),
  (15, 5, 'delete_session', 'Can delete session'),
  (16, 6, 'add_paypalipn', 'Can add PayPal IPN'),
  (17, 6, 'change_paypalipn', 'Can change PayPal IPN'),
  (18, 6, 'delete_paypalipn', 'Can delete PayPal IPN'),
  (19, 7, 'add_acceuilcard', 'Can add acceuil card'),
  (20, 7, 'change_acceuilcard', 'Can change acceuil card'),
  (21, 7, 'delete_acceuilcard', 'Can delete acceuil card'),
  (22, 8, 'add_cardimage', 'Can add card image'),
  (23, 8, 'change_cardimage', 'Can change card image'),
  (24, 8, 'delete_cardimage', 'Can delete card image'),
  (25, 9, 'add_diver', 'Can add diver'),
  (26, 9, 'change_diver', 'Can change diver'),
  (27, 9, 'delete_diver', 'Can delete diver'),
  (28, 10, 'add_boutiqueimage', 'Can add boutique image'),
  (29, 10, 'change_boutiqueimage', 'Can change boutique image'),
  (30, 10, 'delete_boutiqueimage', 'Can delete boutique image'),
  (31, 11, 'add_categorie', 'Can add categorie'),
  (32, 11, 'change_categorie', 'Can change categorie'),
  (33, 11, 'delete_categorie', 'Can delete categorie'),
  (34, 12, 'add_commande', 'Can add commande'),
  (35, 12, 'change_commande', 'Can change commande'),
  (36, 12, 'delete_commande', 'Can delete commande'),
  (37, 13, 'add_contenucommande', 'Can add contenu commande'),
  (38, 13, 'change_contenucommande', 'Can change contenu commande'),
  (39, 13, 'delete_contenucommande', 'Can delete contenu commande'),
  (40, 14, 'add_marque', 'Can add marque'),
  (41, 14, 'change_marque', 'Can change marque'),
  (42, 14, 'delete_marque', 'Can delete marque'),
  (43, 15, 'add_produit', 'Can add produit'),
  (44, 15, 'change_produit', 'Can change produit'),
  (45, 15, 'delete_produit', 'Can delete produit'),
  (46, 16, 'add_souscategorie', 'Can add sous categorie'),
  (47, 16, 'change_souscategorie', 'Can change sous categorie'),
  (48, 16, 'delete_souscategorie', 'Can delete sous categorie'),
  (49, 17, 'add_typesproduit', 'Can add types produit'),
  (50, 17, 'change_typesproduit', 'Can change types produit'),
  (51, 17, 'delete_typesproduit', 'Can delete types produit'),
  (52, 18, 'add_fraisdeport', 'Can add frais de port'),
  (53, 18, 'change_fraisdeport', 'Can change frais de port'),
  (54, 18, 'delete_fraisdeport', 'Can delete frais de port'),
  (55, 19, 'add_user', 'Can add user'),
  (56, 19, 'change_user', 'Can change user'),
  (57, 19, 'delete_user', 'Can delete user'),
  (58, 20, 'add_event', 'Can add event'),
  (59, 20, 'change_event', 'Can change event'),
  (60, 20, 'delete_event', 'Can delete event'),
  (61, 21, 'add_eventimage', 'Can add event image'),
  (62, 21, 'change_eventimage', 'Can change event image'),
  (63, 21, 'delete_eventimage', 'Can delete event image'),
  (64, 22, 'add_eventtype', 'Can add event type'),
  (65, 22, 'change_eventtype', 'Can change event type'),
  (66, 22, 'delete_eventtype', 'Can delete event type');
